---
title: "History"
---

# History of the JSM Diversity Workshop and Mentoring Programs

In 2009, the first JSM Diversity Workship was held in Washington, DC.  The program was initiated by Brian Millen and funded through an ASA Member Initiative grant and additional support from SAS, the Bureau of Labor Statistics, Procter & Gamble, and Eli Lilly and Company. 

The goal of the workshiop was to establish a community of minority statisticians who could support one another's development and success.  This first workshop was a one-day program, focused on skills development and awareness for statisticians at all career levels including undergraduate and graduate students and career professionals. Sesseions and panels covered topics such as career success, graduate school success, networking, successful grant applications, and career searching and interviewing. A 'speed' mentoring session was also held in small groups. 

Positive feedback resulted in a consensus that the program must continue, but also that some changes should be made. One major change was the expansion of the mentoring component.  Over time, the focus of the program became mentoring and addressing the needs of early- to mid-career statisticians from diverse backgrounds.  The Diversity Workshop and Mentoring Program is now offered approximately every three years and includes a full-day workshop targeted at approximately 100 participants, along with one-on-one mentoring and small group sessions throughout the week of JSM. The mentoring program is also offered in all non-workshop years.

More information on the history of the JSM Diversity Workshop and Mentoring Programs can be found [here](http://magazine.amstat.org/blog/2016/09/01/jsmdiversity/).



# Information on Past Workshops and Mentoring Programs

- [2015 Mentoring Program](https://community.amstat.org/cmis/events/dwmp/dmp2015)

- [2016 Workshop and Mentoring Program](https://community.amstat.org/cmis/events/dwmp/dwmp2016)

- [2017 Mentoring Program](https://community.amstat.org/cmis/events/dwmp/dmp2017)

- [2018 Mentoring Program](https://community.amstat.org/cmis/events/dwmp/dmp2018)


